# .github/workflows/build.yml
name: Build and Store Artifacts

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run build
      run: npm run build
      
    - name: Upload public folder
      uses: actions/upload-artifact@v4
      with:
        name: public-${{ github.sha }}
        path: public/
        retention-days: 1
        if-no-files-found: warn
        compression-level: 0
